// packages/svelte/src/lib/ember-link-provider.svelte
<script lang="ts" module>
	const name = 'EMBER_LINK_PROVIDER';

	export function getClientContext<
		P extends Record<string, unknown> = DefaultPresence,
		C extends Record<string, unknown> = DefaultCustomMessageData
	>(): EmberClient<P, C> {
		if (!hasContext(name)) {
			throw new Error('Get client context must be called inside of a client provider');
		}

		return getContext(name);
	}
</script>

<script
	lang="ts"
	generics="P extends Record<string, unknown> = DefaultPresence, C extends Record<string, unknown> = DefaultCustomMessageData"
>
	import { getContext, hasContext, setContext, type Snippet } from 'svelte';
	import {
		createClient,
		type CreateClientOptions,
		type DefaultCustomMessageData,
		type DefaultPresence,
		type EmberClient
	} from '@ember-link/core';

	type Props = { children: Snippet<[]> } & CreateClientOptions;

	const { children, ...clientOptions }: Props = $props();

	const client = createClient<P, C>(clientOptions);

	setContext(name, client);
</script>

{@render children?.()}

// packages/react/lib/ember-link-provider.tsx
import {
  createClient,
  type CreateClientOptions,
  type DefaultCustomMessageData,
  type DefaultPresence,
  type EmberClient
} from '@ember-link/core';
import { createContext, useContext, useMemo, type PropsWithChildren } from 'react';

const ClientContext = createContext<EmberClient | null>(null);

export const useClientOrNull = <
  P extends DefaultPresence,
  C extends DefaultCustomMessageData
>(): EmberClient<P, C> | null => {
  return useContext(ClientContext);
};

export const useClient = <
  P extends DefaultPresence,
  C extends DefaultCustomMessageData
>(): EmberClient<P, C> => {
  const client = useClientOrNull<P, C>();

  if (!client) {
    throw new Error('You must call useClient from inside of a EmberLinkProvider');
  }

  return client;
};

const useEnsureNoEmberLinkProvider = () => {
  const client = useClientOrNull();

  if (client) {
    throw new Error('You cannot nest multiple EmberLinkProviders in the same tree');
  }
};

export const EmberLinkProvider = <
  P extends Record<string, unknown> = DefaultPresence,
  C extends Record<string, unknown> = DefaultCustomMessageData
>({
  children,
  ...options
}: PropsWithChildren<CreateClientOptions>) => {
  useEnsureNoEmberLinkProvider();

  const client = useMemo(() => createClient<P, C>(options), []);

  return <ClientContext.Provider value={client}>{children}</ClientContext.Provider>;
};
